apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: fleet-image-scan-test
  name: fleet-image-scan-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fleet-image-scan-test
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: fleet-image-scan-test
    spec:
      containers:
      - image: registry.gitlab.com/mhassine-talend/fleet-test:0.0.1 # {"$imagescan": "policy-1"}
        name: fleet-test
        resources: {}
status: {}
